create database my_database;
show databases;
use my_database;
create table student_list(ID int, Name varchar(20), F_Name varchar(20), Age int, Address varchar(30));
select *from student_list;
create database library;
use library;
create table books(Book_ID int UNIQUE, Book_Name varchar(30), Author_Name varchar(20));
create table book(Book_ID int, Book_Name varchar(30), Book_Price int);
create table author(Author_ID int, Author_Name varchar(30), Author_publication varchar(30));
select *from books;
select *from book;
select *from author;
show tables;
create database temp;
drop database temp;
drop table books;
insert into book (Book_ID, Book_Name, Book_Price) values (001, 'DBMS', 499);
insert into book (Book_ID, Book_Name, Book_Price) values (002, 'TOC', 299);
delete from book where Book_Price=299;
desc books;
alter table books change Book_Name Book_Name varchar(30) NOT NULL;
create table temp(ID int, name varchar(30), address varchar(30));
desc temp;
alter table temp add unique(ID);
alter table temp add primary key (name);
alter table temp alter address set default "JAIPUR";
alter table temp add check (ID >= 0);
drop table temp;