show databases;
use library;
show tables;
desc temp;
SHOW INDEX FROM temp;
CREATE INDEX idx_Name ON temp (ID);
create table student (ID int primary key, Name varchar(30), Age int);
create table course (C_ID int primary key, C_Name varchar(30), C_Type varchar(30), ID int, foreign key (ID) references student(ID));
desc student;
desc course;
create table Info (ID int, Name varchar(30), City varchar(30));
alter table Info rename My_Info;
show tables;
alter table My_Info add F_Name varchar(30);
select * from My_Info;
desc My_Info;
alter table My_Info add Age int;
alter table My_Info add DOB date after Name;
alter table My_Info add M_Name varchar(30) after City;
alter table My_Info add S_No int first;
alter table My_Info drop column S_No;
alter table My_Info change ID Roll_No int;
alter table My_Info change Roll_No Roll_No varchar(30);
drop table My_Info;